# Generated by Django 2.0.1 on 2018-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('director', models.CharField(max_length=100, verbose_name='Diretor')),
                ('producer', models.CharField(max_length=100, verbose_name='Produtora')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Produzido em')),
                ('rt_score', models.IntegerField(verbose_name='Nota')),
            ],
            options={
                'db_table': 'film',
            },
        ),
    ]
