# Generated by Django 2.0.1 on 2018-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180216_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='folder_image',
            field=models.ImageField(blank=True, null=True, upload_to='films/images', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/images', verbose_name='Imagem'),
        ),
    ]
