# Generated by Django 2.0.1 on 2018-02-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180216_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('director', models.CharField(max_length=100, verbose_name='Diretor')),
                ('temps', models.IntegerField(verbose_name='Temporadas')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Produzido em')),
                ('rt_score', models.IntegerField(verbose_name='Nota')),
                ('image', models.ImageField(blank=True, null=True, upload_to='series/images', verbose_name='Imagem')),
                ('folder_image', models.ImageField(blank=True, null=True, upload_to='series/images', verbose_name='Imagem principal')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'serie',
                'ordering': ['temps'],
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['rt_score']},
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
